# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types:
  - pre-commit
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite

repos:
# Standard pre-commit hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: pretty-format-json
    args:
      [
        --autofix,
        --no-sort-keys]

# Synchronize dependencies upon branch checkout, pull or rebase
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.15
  hooks:
  - id: uv-sync
    args: [ --all-groups ]

# Ruff formatter and auto fix lint error
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.14
  hooks:
  - id: ruff-format
  - id: ruff-check
    args: [ --fix ]

# Pylint check on push
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    stages: [pre-push]
    require_serial: true
    args:
      [
        "-rn", # Only display messages
        "-sn", # Don't display the score
      ]
