# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [pre-commit, pre-push]
repos:
# Standard pre-commit hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: pretty-format-json
    args:
      [
        --autofix,
        --no-sort-keys]

# Ruff for formater and auto fix lint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.14  # Ruff version.
  hooks:
    - id: ruff-check  # Run the linter.
      args: [ --fix ]
    - id: ruff-format  # Run the formatter.

# make sure your uv.lock file is up to date
# even if pyproject.toml file was changed
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.15  # uv version.
  hooks:
  - id: uv-lock

# Pylint pre-push
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    stages: [pre-push]
    require_serial: true
    args:
      [
        "-rn", # Only display messages
        "-sn", # Don't display the score
      ]
