default_install_hook_types:
  - pre-commit
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite

repos:
# Standard pre-commit hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    stages: [pre-commit]

  - id: end-of-file-fixer
    stages: [pre-commit]

  - id: check-yaml
    stages: [pre-commit]

  - id: check-added-large-files
    stages: [pre-commit]

  - id: pretty-format-json
    stages: [pre-commit]
    args: [--autofix, --no-sort-keys]

# Markdown formatter
- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0
  hooks:
  - id: mdformat
    stages: [pre-commit]
    additional_dependencies:
    - mdformat-gfm # GitHub Flavored Markdown

# Synchronize dependencies upon branch checkout, pull or rebase
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.11.15
  hooks:
  - id: uv-sync
    name: uv sync
    stages: [post-checkout, post-merge, post-rewrite]
    args: [--group, lint, --group, hook]

# Ruff formatter and auto fix lint error
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.14
  hooks:
  - id: ruff-format
    name: ruff format
    types: [python]
    stages: [pre-commit]

  - id: ruff-check
    name: ruff check
    types: [python]
    stages: [pre-commit]
    args: [ --fix ]

# Pylint check on push
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    stages: [pre-push]
    require_serial: true
    args: ["-rn", "-sn",] # Only display messages
