[project]
name = "keytik"
version = "2.3.6"
description = "A Powerful Multi-Profile Key Mapper, Clicker, Macro, and More."
authors = [
    {name = "Fajar Rahmad Jaya",email = "Fajar.Rahmad.Jaya.Profile@gmail.com"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "keyboard (>=0.13.5,<0.14.0)",
    "requests>=2.34.2,<3.0.0",
    "markdown (>=3.10.2,<4.0.0)",
    "psutil (>=7.2.2,<8.0.0)",
    "pyside6==6.11.1",
    "pynput>=1.8.2,<2.0.0",
    "pywin32>=312,<313",
    "winshell (>=0.6,<0.7)",
    "win32mica>=3.0",
    "qt-themes>=0.4.0",
    "winaccent>=2.1.0",
    "catppuccin>=2.5.0",
]

[dependency-groups]
lint = [
    "pylint>=4.0.6",
    "ruff>=0.15.20",
]
hook = [
    "pre-commit>=4.6.0",
]
pyinstaller = [
    "pyinstaller>=6.21.0",
]
changelog-generator = [
    "git-cliff>=2.13.1",
]

# Build system
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["keytik"]

# Include data folder
[tool.hatch.build]
include = [
    "keytik/_internal/**",
]

# ----------------------------- Tools -----------------------------
# Ruff
[tool.ruff.lint]
select = [
    "PL", # pylint
    "D", # pydocstyle
    "RUF", # Ruff-specific rules
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]

# Changelog generator
[tool.git-cliff.changelog]
body = """
{% if version %}\
    ## KeyTik v{{ version | trim_start_matches(pat="v") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# Render body even when there are no releases to process.
render_always = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = []
# output file path
output = "CHANGELOG.md"

[tool.git-cliff.git]
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# Require all commits to be conventional.
# Takes precedence over filter_unconventional.
require_conventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = []
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = false
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->New Features" },
    { message = "^feat(", group = "<!-- 2 -->Improvements" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Fail on a commit that is not matched by any commit parser.
fail_on_unmatched_commit = false
# An array of link parsers for extracting external references, and turning them into URLs, using regex.
link_parsers = []
# Include only the tags that belong to the current branch.
use_branch_tags = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order commits topologically instead of chronologically.
topo_order_commits = true
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"
# Process submodules commits
recurse_submodules = false
