[project]
name = "keytik"
version = "2.3.6"
description = "A Powerful Multi-Profile Key Mapper, Clicker, Macro, and More."
authors = [
    {name = "Fajar Rahmad Jaya",email = "Fajar.Rahmad.Jaya.Profile@gmail.com"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "keyboard (>=0.13.5,<0.14.0)",
    "requests>=2.34.2,<3.0.0",
    "markdown (>=3.10.2,<4.0.0)",
    "psutil (>=7.2.2,<8.0.0)",
    "pyside6==6.11.1",
    "pynput>=1.8.2,<2.0.0",
    "pywin32>=312,<313",
    "winshell (>=0.6,<0.7)",
    "win32mica>=3.0",
    "qt-themes>=0.4.0",
    "winaccent>=2.1.0",
    "catppuccin>=2.5.0",
    "pyqcodeeditor>=0.3.7",
]

[dependency-groups]
lint = [
    "pylint>=4.0.6",
    "ruff>=0.16.0",
]
hook = [
    "pre-commit>=4.6.1",
]

# Build system
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["keytik"]

# Include data folder
[tool.hatch.build]
include = [
    "keytik/_internal/**",
]

# ----------------------------- Tools -----------------------------
# --- Ruff ---
[tool.ruff.lint]
select = [
    "PL", # pylint
    "D", # pydocstyle
    "RUF", # Ruff-specific rules
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]

ignore = [
    "D401", # non-imperative-mood
    "D107", # undocumented-public-init
    "D203", # incorrect-blank-line-before-class (Compatibility with D211)
    "D213", # multi-line-summary-second-line (Compatibility with D212)
]

extend-safe-fixes = [
    "D400", # missing-trailing-period
]

[tool.ruff]
line-length = 100 # Match pylint default

[tool.pylint.format]
max-line-length = 100 # Match pylint default

# --- Changelog generator ---
[tool.git-cliff.changelog]
body = """
{% if version %}\
    ## KeyTik v{{ version | trim_start_matches(pat="v") }} Preview
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
output = "CHANGELOG.md"

[tool.git-cliff.git]
commit_parsers = [
    { message = "^feat\\([^)]*\\):", group = "<!-- 1 -->Improvements" },
    { message = "^feat", group = "<!-- 0 -->New Features" },
    { message = "^fix", group = "<!-- 2 -->Fixes" },
    { message = "^chore", skip = true },
    { message = "^refactor", skip = true },
    { message = "^style", skip = true },
    { message = "^docs", skip = true },
]
