name: Feature Suggestion
description: Suggest a feature.
title: "Feature: "
labels: [Feature]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
      placeholder: |
        Example:
          Add an option to ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: |
        Additional details and attachments.
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have filled out all of the requested information in this form.
          required: true
