name: Question
description: Ask any question about KeyTik.
title: "Question: "
labels: [Question]
body:
  - type: textarea
    id: question-description
    attributes:
      label: Describe your question
      placeholder: |
        Example:
          How to ...
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have filled out all of the requested information in this form.
          required: true
