name: Pylint

on:
   pull_request:
     branches: [ "main" ]

jobs:
  lint:
    name: Checking Pylint 
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --locked --all-groups
    
      - name: Run Pylint
        run: uv run pylint ./src
        continue-on-error: false
